server:
  tomcat:
    max-threads: 200
  port: 8080
spring:
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:6306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: abc123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  http:
    multipart:
      max-file-size: 10MB
  redis:
    database: 0
    host: 192.168.242.129
    port: 6379
    pool:
      min-idle: 8
      max-idle: 50
      max-active: 200
    timeout: 0

logging:
  level:
    root: info
    com.ysp: info
  file: log/blog-pro.log



comment.avatar: /images/avatar.png